services:
  postgres:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "${LACI_POSTGRES_DB}"
      POSTGRES_USER: "${LACI_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${LACI_POSTGRES_PASSWORD}"
    volumes:
      - ../data/postgresql/:/var/lib/postgresql/data
      - postgres_socket:/var/run/postgresql:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${LACI_POSTGRES_USER}"]
      interval: 5s
      start_period: 5s
      timeout: 5s
      retries: 5

  haproxy:
    image: docker.io/haproxy:latest
    restart: always
    ports: 
      - 6000:6000/tcp
    volumes:
      - ../config/sharded/haproxy-shards.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      laci-server:
        condition: service_healthy
        
  redis:
    image: docker.io/redis:latest
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save \"\" --appendonly no --requirepass $${LACI_REDIS_PASSWORD}"]
    volumes:
      - cache:/data

  laci-server:
    image: lacisynchroni/server:latest
    pull_policy: never
    restart: on-failure
    environment:
      LaciSynchroni__CdnFullUrl: "${LACI_CDNURL}"
    volumes:
      - ../config/sharded/server-shard-main.json:/opt/LaciSynchroni/Server/appsettings.json
      - ../log/server-shard-main/:/opt/LaciSynchroni/Server/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:6000/health || exit 1"]
      retries: 60
      start_period: 10s
      timeout: 1s

  laci-shard-1:
    image: lacisynchroni/server:latest
    pull_policy: never
    restart: on-failure
    volumes:
      - ../config/sharded/server-shard-1.json:/opt/LaciSynchroni/Server/appsettings.json
      - ../log/server-shard-1/:/opt/LaciSynchroni/Server/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
    depends_on:
      laci-server:
        condition: service_healthy

  laci-shard-2:
    image: lacisynchroni/server:latest
    pull_policy: never
    restart: on-failure
    volumes:
      - ../config/sharded/server-shard-2.json:/opt/LaciSynchroni/Server/appsettings.json
      - ../log/server-shard-2/:/opt/LaciSynchroni/Server/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
    depends_on:
      laci-server:
        condition: service_healthy

  laci-services:
    image: lacisynchroni/services:latest
    pull_policy: never
    restart: on-failure
    volumes:
      - ../config/standalone/services-standalone.json:/opt/LaciSynchroni/Services/appsettings.json
      - ../log/services-standalone/:/opt/LaciSynchroni/Services/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
    depends_on:
      laci-server:
        condition: service_healthy

  laci-files:
    image: lacisynchroni/staticfilesserver:latest
    pull_policy: never
    restart: on-failure
    ports:
      - 6200:6200/tcp
    environment:
      LaciSynchroni__CdnShardConfiguration__0__CdnFullUrl: "${LACI_CDNURL}"
      LaciSynchroni__CdnShardConfiguration__0__FileMatch: "^[012345678]"
      LaciSynchroni__CdnShardConfiguration__1__CdnFullUrl: "${LACI_CDNURL2}"
      LaciSynchroni__CdnShardConfiguration__1__FileMatch: "^[789ABCDEF]"
    volumes:
      - ../config/sharded/files-shard-main.json:/opt/LaciSynchroni/StaticFilesServer/appsettings.json
      - ../log/files-standalone/:/opt/LaciSynchroni/StaticFilesServer/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
      - ../data/files-shard-main/:/lacicache/:rw
    depends_on:
      laci-server:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:6200/health || exit 1
      retries: 60
      start_period: 10s
      timeout: 1s

  laci-files-shard-1:
    image: lacisynchroni/staticfilesserver:latest
    pull_policy: never
    restart: on-failure
    volumes:
      - ../config/sharded/files-shard-1.json:/opt/LaciSynchroni/StaticFilesServer/appsettings.json
      - ../log/files-shard-1/:/opt/LaciSynchroni/StaticFilesServer/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
      - ../data/files-shard-1/:/lacicache/:rw
    ports: 
      - 6201:6200/tcp
    depends_on:
      laci-files:
        condition: service_healthy

  laci-files-shard-2:
    image: lacisynchroni/staticfilesserver:latest
    pull_policy: never
    restart: on-failure
    volumes:
      - ../config/sharded/files-shard-2.json:/opt/LaciSynchroni/StaticFilesServer/appsettings.json
      - ../log/files-shard-2/:/opt/LaciSynchroni/StaticFilesServer/logs/:rw
      - postgres_socket:/var/run/postgresql/:rw
      - ../data/files-shard-2/:/lacicache/:rw
    ports: 
      - 6202:6200/tcp
    depends_on:
      laci-files:
        condition: service_healthy

volumes:
  cache:
    driver: local
  postgres_socket:
